default: &default
  adapter: postgresql
  encoding: unicode
  username: regoky
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ankibooks2_development

test:
  <<: *default
  database: ankibooks2_test

production:
  <<: *default
  database: ankibooks2_production
  username: ankibooks2
  password: <%= ENV['ANKIBOOKS2_DATABASE_PASSWORD'] %>